language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
  - "stable"

# Use faster Docker architecture on Travis.
sudo: false

script:        npm run-script lint && npm test
after_success: npm run coveralls
